name: Daily Code Execution and Deploy

on:
  schedule:
    # 日本時間 8:00, 8:30, 8:40, 8:50, 8:55 (UTCでは 23:00, 23:30, 23:40, 23:50, 23:55)
    # 日本時間 18:00, 18:30, 18:40, 18:50, 18:55 (UTCでは 9:00, 9:30, 9:40, 9:50, 9:55)
    # - cron: '0,30,40,50,55 23 * * *'
    - cron: '0,30,40,50,55 23 * * *'
  workflow_dispatch: # 手動実行用ボタン

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python # または実行したい言語
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run code
        run: |
          pip install numpy pandas yfinance
          python run_task.py 

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/logs.json
          git commit -m "Add new log: $(date)"
          git push
